resources:
- ../base
namePrefix: prd-
nameSuffix: -v1
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx-deployment
    spec:
      template:
        spec:
          containers:
          - name: nginx
            image: nginx:1.27
- target:
    kind: Service
    name: nginx-service
  patch: |-
    - op: replace
      path: /spec/type
      value: NodePort
    - op: replace
      path: /spec/ports
      value:
        - protocol: TCP
          port: 8080
          targetPort: 8080
configMapGenerator:
- name: the-map
  literals:
    - altGreeting=Good Morning!
    - enableRisky="false"
commonLabels:
  app: hello