resources:
- ../base
namePrefix: smp-
nameSuffix: -v1
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx-deployment
    spec:
      template:
        spec:
          containers:
          - name: nginx
            image: nginx:latest
    